export type RootStackParamList = {
  Home: undefined;
  CasualSplit: undefined;
  Capture: { openGalleryOnMount?: boolean } | undefined;
  ExtractedItems: undefined;
  ExtractionFailed: undefined;
  ManualEntry: undefined;
  ItemAssignment: undefined;
  Review: undefined;
  FinalSplit: undefined;
  History: undefined;
  HistoryDetail: { entryId: string };
  EmailEntry: undefined;
  OtpVerify: { email: string };
  GroupList: undefined;
  Account: { requireName?: boolean } | undefined;
  CreateGroup: undefined;
  GroupDetail: { groupId: string };
  ExpenseDetail: { groupId: string; expenseId: string };
  ExpenseEdit: { groupId: string; expenseId: string };
  InviteMember: { groupId: string };
  SettleUp: { groupId: string };
};
