export type RootStackParamList = {
  Home: undefined;
  Capture: { openGalleryOnMount?: boolean } | undefined;
  ExtractedItems: undefined;
  ExtractionFailed: undefined;
  ManualEntry: undefined;
  TaxService: undefined;
  ItemAssignment: undefined;
  Review: undefined;
  FinalSplit: undefined;
  History: undefined;
  HistoryDetail: { entryId: string };
  PhoneEntry: undefined;
  OtpVerify: { phoneE164: string };
  GroupList: undefined;
  CreateGroup: undefined;
  GroupDetail: { groupId: string };
  InviteMember: { groupId: string };
  SettleUp: { groupId: string };
};
